version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  test:
    executor: cypress/base-12-14-0
    steps:
      - checkout
      - cypress/install:
          # we only have 1 CI job, no need to save the workspace
          no-workspace: true
      - run:
          name: Netlify Build 🏗
          command: npx netlify build

workflows:
  version: 2
  test:
    jobs:
      - test
